# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6l1Y02EiTTb14oN9DpoDXeFsgur50VU
"""

import seaborn as sns 
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

tips =sns.load_dataset('tips')

tips.head()

tips.shape

sns.barplot(x='sex', y='total_bill', data=tips,estimator=np.std);

sns.countplot(x='sex' , data=tips);

sns.countplot(x='time', data=tips);

sns.boxplot(x='day', y='total_bill', data=tips);

sns.boxplot(x='day', y='total_bill', data=tips, hue='smoker');

sns.boxplot(x='day', y='total_bill', data=tips, hue='sex');

sns.violinplot(x='day', y='total_bill' , data=tips);

sns.violinplot(x='day', y='total_bill' ,hue='sex', data=tips, split=True);

sns.distplot(tips['total_bill']);

sns.distplot(tips['total_bill'],kde=False);

sns.kdeplot(tips['total_bill']);

sns.jointplot(x='total_bill', y='tip' , data=tips); #by difficult the Jointplot is scatter

sns.jointplot(x='total_bill', y='tip' , data=tips, kind='hex'); #now let use other kind

sns.pairplot(tips);

sns.pairplot(tips, hue='sex');

corr_rel=tips.corr()
corr_rel

sns.heatmap(corr_rel)

sns.heatmap(corr_rel, annot=True);

#Let load another Dataset

flights = sns.load_dataset('flights');

flights

flights.columns

fp= flights.pivot_table(index='month' , columns='year', values='passengers'      )

fp

sns.heatmap(fp);

#ANOTHER TITANIC DATASET

tit= sns.load_dataset('titanic')

tit

sns.jointplot(x='age', y='survived' , data=tit);

